### ISSUE TITLE
Terraform 0.12 support?

### ISSUE THREAD

**Issue by innovia** [gruntwork-io/terratest#252]
Hi

Is terratest supports terrform 0.12? I wanna play with the beta of 0.12

**Comment by brikis98** [comment]
We have not tested it with Terraform 0.12 yet, so honestly, I'm not sure. Feel free to give it a shot and let us know 😁

**Comment by innovia** [comment]
looks like it's working just fine  (all you do is run a command and not import the actual terraform lib)

i have basic syntax error...

**Comment by tnguyen14** [comment]
I follow the examples in https://github.com/gruntwork-io/terratest/blob/master/test/terraform_azure_example_test.go and that uses the `terraform` module, which doesn't work with 0.12.

How should I make it work with terraform 0.12?

**Comment by yorinasub17** [comment]
Hi can you share:

- Go version
- The method you are using to pull in terratest, and the version of terratest
- The specific error you are seeing

**Comment by tnguyen14** [comment]
Thanks for the response @yorinasub17 

Go version: 1.14
Terratest version 0.26.0 from go modules

The error:

```
TestAure 2020-03-17T13:28:08-04:00 retry.go:72: terraform [init -upgrade=false]
TestAure 2020-03-17T13:28:08-04:00 command.go:87: Running command terraform with args [init -upgrade=false]
TestAure 2020-03-17T13:28:09-04:00 command.go:158: There are some problems with the configuration, described below.
TestAure 2020-03-17T13:28:09-04:00 command.go:158:
TestAure 2020-03-17T13:28:09-04:00 command.go:158: The Terraform configuration must be valid before initialization so that
TestAure 2020-03-17T13:28:09-04:00 command.go:158: Terraform can determine which modules and providers need to be installed.
TestAure 2020-03-17T13:28:09-04:00 command.go:158:
TestAure 2020-03-17T13:28:09-04:00 command.go:158: Error: Error parsing /home/tri/github/azure-test/main.tf: At 17:25: Unknown token: 17:25 IDENT var.resource_group_name
```

The terraform resource in question looks like this:

```hcl
resource "azurerm_network_interface" "instance_nic" {
  name = "${var.instance_name}-nic"
  resource_group_name = var.resource_group_name
  location = var.location

  ip_configuration {
    name = local.nic_ip_configuration_name
    subnet_id = local.subnet_id
    private_ip_address_allocation = "Dynamic"
  }
}
```

**Comment by yorinasub17** [comment]
> Error parsing /home/tri/github/azure-test/main.tf: At 17:25: Unknown token: 17:25 IDENT var.resource_group_name

This error looks very similar to the error you get when you run terraform `0.11.x` against terraform `0.12.x` code. Make sure the terraform version you have installed on your machine running `go test` is using terraform 12.

**Comment by tnguyen14** [comment]
I thought so, which is why I found this thread. Terraform version is 0.12:

```
:; terraform -v
Terraform v0.12.21
+ provider.azurerm v2.0.0
```

**Comment by yorinasub17** [comment]
Terratest just calls out to terraform in a subshell and does not embed terraform, so it most likely is resolving to a different terraform binary than your shell. Are you by chance in an environment with multiple terraform versions? If so, what is your mechanism for switching versions?

**Comment by tnguyen14** [comment]
Actually, that's most likely what's happening. How does terratest resolve PATH? 

I have terraform 12 in the local directory and my $PATH env variable is set to resolve the local dir first.

**Comment by yorinasub17** [comment]
Hmm that should work. It uses golang's `os/exec` package to spawn the subprocess, which should inherit all the environment variables of the current shell. It might have to do with the fact that it is spawning in a pseudo shell as opposed to a real shell.

Regardless, one workaround is to direct terratest to use the tf12 version that is installed by setting the `TerraformBinary` option: https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L11

**Comment by alexcurtin** [comment]
I am seeing similar issues, do you know what release of `terratest` works with TF `0.12.X`?

**Comment by yorinasub17** [comment]
Terratest supported TF 0.12.X starting with version `v0.15.8`.

**Comment by alexcurtin** [comment]
Thanks for the prompt reply, I am using https://github.com/hashicorp/terraform-aws-vault/blob/98e501d360ae21d465a8de0d1b6b2a1df5135503/test/vault_helpers.go#L79 to mergemaps passed into:

```

	terraformOptions := &terraform.Options{
		TerraformDir: examplesDir,
		Vars: mergeMaps(terraformVars, map[string]interface{}{
```

but when terratest wraps `terraform` binary I am getting:

```
 Error: Invalid value for input variable
 The argument -var="shard_count=..." does not contain a valid value for
: variable "shard_count": a number is required.
```

It seems like terratest vars are not passing the new type of `number` properly to `-vars`? Is there something special I need to do for terratest to recognize the vars passed to terraform are of type number, not string or is it ok to pass a number in quotes? e.g. `-var shard_count="3"`

**Comment by yorinasub17** [comment]
It should work when you don't go through `mergeMaps` and directly pass a map that uses a number for the value (e.g., `map[string]interface{}{"shard_count": 3}`). It's a bit hard to say what's going on without seeing what you have in `terraformVars` or the second `map`, but my guess is that the underlying type is being lost when you go through `mergeMaps`.
